version = 0.1
[default.deploy.parameters]
stack_name = "kd3"
resolve_s3 = true
s3_prefix = "kd3"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["CloneRepo=454445151329.dkr.ecr.ap-south-1.amazonaws.com/kd32b1ccb53/clonerepo9c245c20repo"]
